odecov:
  notify:
    require_ci_to_pass: yes
comment:
  layout: "header, changes, diff, sunburst"

coverage:
  ignore:
  - Pods/.*
  - Applications/Xcode.app/.*
  - vendor/.*
  - Carthage/.*
  - .*Tests.m
  - .*Tests.swift
  status:
    patch: false
